### ISSUE TITLE
Images need to have descriptive alt text

### ISSUE THREAD

**Issue by lmcneel** [lmcneel/stalks#221]
![image](https://user-images.githubusercontent.com/2047327/42547382-6f255070-8487-11e8-8404-48d3d1921df8.png)

I'm not for sure who is working on the top nav, but the main logo needs to have alt="Text Logo for Stock Market Pets in .... style typeface, white on green bg"

When writing alt text, you want to think about describing the image for someone who can't see.

**Comment by coolcaliente** [comment]
updated this and pushed to the public branch :)
