### ISSUE TITLE
Trading routes - Buy/Sell/Fetch Price

### ISSUE THREAD

**Issue by ajlaroche** [lmcneel/stalks#28]
Create market transaction routes which start with the user front end order to buy or sell stock.

- [ ] Front end code that takes user input: ticker symbol and number of 

- [ ] Work with front end developer to build order form

- [ ] Front end route to send user request to backend

- [ ] Back end API route to 3rd party site to fetch last quoted price for given ticker

- [ ] Check sufficient user balance

- [ ] If user balance sufficient, database route to send buy/sell order, ticker, number of shares, and quote price to database

- [ ] Update user balance in database

- [ ] Update user portfolio in database

- [ ] Send feedback to front-end: transaction complete or insufficient funds, new balance

**Comment by Cdemeke1227** [comment]
This list will be broken down into separate issues specified below:
Please create new issue-branches under the trading branch to work on them.

Chris:
  Work with front end developer to build order form
  Create DB Model
  Start Seeds

Anthony:
  Front end route to send user request to backend
  Back end API route to 3rd party site to fetch last quoted price for given ticker
  Check sufficient user balance
  If user balance sufficient, database route to send buy/sell order, ticker, number of shares, and 
  quote price to database

Korshid:
  Update user balance in database
  Update user portfolio in database
  Send feedback to front-end: transaction complete or insufficient funds, new balance

**Comment by Cdemeke1227** [comment]
Trading/Mongo Update: July, 2, 2018

- Becca/Shelby Follow up - Help information will be stored in mongo
- Alex Follow up - Forum Message Board, clan id reference, on message board topic name.  
- Ross Follow up -Scores and Leader board?,  FrontEnd Components that are on portfolio, User ID - 
- Oluwatoyin Follow up - Public pages mongo dev teams.

Team
- Mongo stores MySQL User ID
- 
- Portfolio Metrics Functions and Util
- 
- K Multiple ROI functions
