### ISSUE TITLE
Decide what information to include on the User Profile and which information is editable/changeable

### ISSUE THREAD

**Issue by tranmike270** [lmcneel/stalks#37]
Anything with a * next to it, is explained down bellow in comments
This might include: 
- [x] Email
- [x] Name
- [x] User Name
- [x] Rank/Status
- [x] Pet Info
- [x] Length of Account 
- [x] Option to Change Pet/Pet Name *
- [x] Link to transaction history 
- [x] Link to Delete Account *
- [x] Edit Link (indvidual fields or otherwise)
- [x] Change Email Link *
- [x] Change Username Link *
- [x] Change Password link *
- [x] Verification *
- [x] Submit a Ticket Link *

**Comment by tranmike270** [comment]
Everything with  start will be explained ...

- **Link to Delete Account** - I personally do not support having a link allowing a user to delete their account. Simply from my time on reddit game forums, and people 'accidentally deleting their accounts' and demanding compensation for their time put in.   
- **Pause Account Link** - As an alternative to deleting an account, users could be able to put their account on pause, meaning all current activity will be halted. What I mean is, for example all open orders, won't be closed, however, they're put on temporary hold until the user decides to unpause their account. That way, if users expect any hiatus from the game they can simply pause, then unpause right where the left off no matter how long ago the pause was.
- **Change Email Link** - I believe changing email or  should require password verification in order to change it. Of course this shouldn't be an issue too often. Only thing I suggest would be email verification in order to solidify the email change.
- **Change Username Link** - A users username should be special and unique to them, also it gets very extensive to change in all out databases. So I believe there should be a price, not necessarily cash payment, but like a good amount of in game currency.
- **Change Password Link** - Password changing should require an email verification, as long as retyping password. simple

### **IF ANYONE THINKS ANYTHING ELSE SHOULD BE HERE OR SHOULD NOT BE HERE PLEASE GIVE ME YOUR INPUT SO I CAN MAKE ADJUSTMENTS**

**Comment by vasisko** [comment]
What will you include in the Transaction History?  If it is only portfolio-related, a link to the portfolio page may be all you need.  I agree with pausing the account vs deleting.

**Comment by lmcneel** [comment]
Link to Delete Account - I personally do not support having a link allowing a user to delete their account. Simply from my time on reddit game forums, and people 'accidentally deleting their accounts' and demanding compensation for their time put in. 

You have to have the above for GDPR - No Option. The site can't be used by European Users otherwise.

**Comment by lmcneel** [comment]
@vasisko 

Transaction history could be its own page, but that would show real money purchases if we get there.

Different than Portfolio.

**Comment by tranmike270** [comment]
@vasisko Sorry I meant just a link to it
